spring.config.import=optional:file:./application-local.properties

server.port=8081
server.servlet.session.persistent=false
spring.application.name=WebProject_De04

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WebDB_De04;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=temporary8386@gmail.com
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# VNPay Sandbox
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:8081/payment/vnpay-return}
vnpay.tmn-code=${VNPAY_TMN_CODE:}
vnpay.hash-secret=${VNPAY_HASH_SECRET:}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}